const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Yulia",
      email: "editor@example.com",
      password: "123456",
      role: "editor",
    },
    {
      name: "Jane",
      email: "jane@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      name: "Rose Hips Peel / Bulgaria",
      slug: "polo-sporting-stretch-shirt",
      category: "Herbal Tea",
      description:
        "Rose hip varies from light to dark red, in autumn a real eye-catcher in the woods. The plant originates in Europe, The Middle East and North Africa. The rose hip is dried in wood-burning stoves, it is especially suitable as a single fruit  for a delicious and thirst-quenching infusion. In a fruit tea blends it is one of the most important  ingredients and almost indispensible.",
      images: [
        "/images/sample-products/pu-8.jpg",
        "/images/sample-products/pu-7.jpg",
      ],
      price: 4.5,
      brand: "Bulgaria",
      rating: 4.5,
      numReviews: 10,
      stock: 15,
      isFeatured: true,
      banner: "/images/banner-1.jpg",
    },
    {
      name: "Jade Snow/China",
      slug: "jade-snow-china",
      category: "Green Tea",
      description:
        "This area of Yunnan is known for its ability to produce needle leaves and other unusual shapes. This kind is special because three harvest periods of a tea are mixed together. A firework for the palate.",
      images: [
        "/images/sample-products/pu-1.jpg",
        "/images/sample-products/pu-2.jpg",
      ],
      price: 7.9,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "/images/banner-2.jpg",
    },
    {
      name: "Box of Tea Assortment - Flavored Green Tea",
      slug: "flavored-green-tea",
      category: "Flavored Green",
      description:
        "Having chosen a box of tea assortment, you can try 5 types of tea and find your favorite taste.",
      images: [
        "/images/sample-products/pu-3.jpg",
        "/images/sample-products/pu-4.jpg",
      ],
      price: 18.8,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Christmas Tea",
      slug: "christmas-tea",
      category: "Black Tea",
      description:
        "This harmonius China-Ceylon blend was enriched with almond pieces and different blossoms.Selected spices and ingredients like cloves and orange peel harmonise perfectly.The delicious walnut finally finds its Christmassy”goal”.A delightfull blend to warm up during the cold season.",
      images: [
        "/images/sample-products/pu-5.jpg",
        "/images/sample-products/pu-6.jpg",
      ],
      price: 6.3,
      brand: "Black",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 79.99,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 99.99,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
