const sampleDataProducts = [
  {
    name: "Alpiskiy Lug",
    slug: "alpiskiy-lug",
    category: "Herbal Tea",
    description:
      "Rose hip varies from light to dark red, in autumn a real eye-catcher in the woods. The plant originates in Europe, The Middle East and North Africa. The rose hip is dried in wood-burning stoves, it is especially suitable as a single fruit  for a delicious and thirst-quenching infusion. In a fruit tea blends it is one of the most important  ingredients and almost indispensible.",
    images: [
      "/images/products/p-01-1.jpg",
      "/images/products/p-01-2.jpg",
      "/images/products/p-01-3.jpg",
    ],
    price: 4.5,
    brand: "Bulgaria",
    rating: 4.5,
    numReviews: 10,
    stock: 15,
    isFeatured: true,
    banner: "/images/banner-1.jpg",
  },
  {
    name: "Sir Charles Grey",
    slug: "sir-charles-grey",
    category: "Black Tea",
    description:
      "This area of Yunnan is known for its ability to produce needle leaves and other unusual shapes. This kind is special because three harvest periods of a tea are mixed together. A firework for the palate.",
    images: [
      "/images/products/p-02-1.jpg",
      "/images/products/p-02-2.jpg",
      "/images/products/p-02-3.jpg",
    ],
    price: 7.9,
    brand: "Brooks Brothers",
    rating: 4.2,
    numReviews: 8,
    stock: 10,
    isFeatured: true,
    banner: "/images/banner-2.jpg",
  },
  {
    name: "English Aristokrat",
    slug: "english-aristokrat",
    category: "Flavored Green",
    description:
      "Having chosen a box of tea assortment, you can try 5 types of tea and find your favorite taste.",
    images: [
      "/images/products/p-03-1.jpg",
      "/images/products/p-03-2.jpg",
      "/images/products/p-03-3.jpg",
    ],
    price: 18.8,
    brand: "Tommy Hilfiger",
    rating: 4.9,
    numReviews: 3,
    stock: 0,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Bryzgy Shampanskogo",
    slug: "bryzgy-shampanskogo",
    category: "Black Tea",
    description:
      "This harmonius China-Ceylon blend was enriched with almond pieces and different blossoms.Selected spices and ingredients like cloves and orange peel harmonise perfectly.The delicious walnut finally finds its Christmassy”goal”.A delightfull blend to warm up during the cold season.",
    images: [
      "/images/products/p-04-1.jpg",
      "/images/products/p-04-2.jpg",
      "/images/products/p-04-3.jpg",
    ],
    price: 6.3,
    brand: "Black",
    rating: 3.6,
    numReviews: 5,
    stock: 10,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Cleopatra Night",
    slug: "cleopatra-night",
    category: "Black Tea",
    description: "Iconic Polo design with refined oxford fabric",
    images: [
      "/images/products/p-05-1.jpg",
      "/images/products/p-05-2.jpg",
      "/images/products/p-05-3.jpg",
      "/images/products/p-05-4.jpg",
      "/images/products/p-05-5.jpg",
    ],
    price: 79.99,
    brand: "Polo",
    rating: 4.7,
    numReviews: 18,
    stock: 6,
    isFeatured: false,
    banner: null,
  },
  {
    name: "Exclusive Gun Powder",
    slug: "exclusive-gun-powder",
    category: "Powder Tea",
    description: "Soft, stylish, and perfect for laid-back days",
    images: [
      "/images/products/p-06-1.jpg",
      "/images/products/p-06-2.jpg",
      "/images/products/p-06-3.jpg",
      "/images/products/p-06-4.jpg",
    ],
    price: 99.99,
    brand: "Polo",
    rating: 4.6,
    numReviews: 12,
    stock: 8,
    isFeatured: true,
    banner: null,
  },
  {
    name: "King of Jusmine",
    slug: "king-of-jusmine",
    category: "Herbal Tea",
    description: "Soft, stylish, and perfect for laid-back days",
    images: [
      "/images/products/p-04-1.jpg",
      "/images/products/p-04-2.jpg",
      "/images/products/p-04-3.jpg",
    ],
    price: 99.99,
    brand: "Polo",
    rating: 4.6,
    numReviews: 12,
    stock: 8,
    isFeatured: true,
    banner: null,
  },
  {
    name: "Bergamont",
    slug: "bergamont",
    category: "Herbal Tea",
    description: "Soft, stylish, and perfect for laid-back days",
    images: [
      "/images/products/p-04-1.jpg",
      "/images/products/p-04-2.jpg",
      "/images/products/p-04-3.jpg",
    ],
    price: 99.99,
    brand: "Polo",
    rating: 4.6,
    numReviews: 12,
    stock: 8,
    isFeatured: true,
    banner: null,
  },
  {
    name: "Karpatian Tea",
    slug: "karpatian-tea",
    category: "Herbal Tea",
    description: "Soft, stylish, and perfect for laid-back days",
    images: [
      "/images/products/p-04-1.jpg",
      "/images/products/p-04-2.jpg",
      "/images/products/p-04-3.jpg",
    ],
    price: 99.99,
    brand: "Polo",
    rating: 4.6,
    numReviews: 12,
    stock: 8,
    isFeatured: true,
    banner: null,
  },
  {
    name: "1001 Nights",
    slug: "1001-nights",
    category: "Herbal Tea",
    description: "Soft, stylish, and perfect for laid-back days",
    images: [
      "/images/products/p-04-1.jpg",
      "/images/products/p-04-2.jpg",
      "/images/products/p-04-3.jpg",
    ],
    price: 99.99,
    brand: "Polo",
    rating: 4.6,
    numReviews: 12,
    stock: 8,
    isFeatured: true,
    banner: null,
  },
  {
    name: "Sousep",
    slug: "sousep",
    category: "Herbal Tea",
    description: "Soft, stylish, and perfect for laid-back days",
    images: [
      "/images/products/p-04-1.jpg",
      "/images/products/p-04-2.jpg",
      "/images/products/p-04-3.jpg",
    ],
    price: 99.99,
    brand: "Polo",
    rating: 4.6,
    numReviews: 12,
    stock: 8,
    isFeatured: true,
    banner: null,
  },
];

export default sampleDataProducts;
